Separate select for SVN and Git repositories
Extends the repository wizard state machine to ask for
subversion and git separately in order to allow configuring one or both
vendors on their own.

diff --git a/bin/configure b/bin/configure
--- a/bin/configure
+++ b/bin/configure
@@ -20,7 +20,58 @@ input_params() {
 	fi
 
 	wiz_put "repositories/api-key"
+
+	if wiz_ask ; then
+		STATE="svn_setup"
+	else
+		echo "Aborting configuration."
+		exit 1
+	fi
+}
+
+select_svn_installation() {
+	wiz_put "repositories/svn-install"
+	if wiz_ask ; then
+		RET=$(wiz_get "repositories/svn-install")
+		if [ "$RET" = "install" ] ; then
+			STATE="svn_params"
+		else
+			STATE="git_setup"
+		fi
+	else
+		STATE="done"
+		echo "SVN configuration canceled."
+		exit 1
+	fi
+}
+
+input_svn_params() {
 	wiz_put "repositories/svn-path"
+	if wiz_ask ; then
+		STATE="git_setup"
+	else
+		echo "Aborting configuration."
+		exit 1
+	fi
+}
+
+select_git_installation() {
+	wiz_put "repositories/git-install"
+	if wiz_ask ; then
+		RET=$(wiz_get "repositories/git-install")
+		if [ "$RET" = "install" ] ; then
+			STATE="git_params"
+		else
+			STATE="done"
+		fi
+	else
+		STATE="done"
+		echo "Git configuration canceled."
+		exit 1
+	fi
+}
+
+input_git_params() {
 	wiz_put "repositories/git-path"
 	wiz_put "repositories/git-http-backend"
 
@@ -39,6 +90,18 @@ state_machine() {
 			;;
 		"params")
 			input_params
+			;;
+		"svn_setup")
+			select_svn_installation
+			;;
+		"svn_params")
+			input_svn_params
+			;;
+		"git_setup")
+			select_git_installation
+			;;
+		"git_params")
+			input_git_params
 			;;
 		"done")
 			echo "DONE"
